namespaces:
  - default
  - kube-system
image_filter_regex_exclude:
snyk_org_mapping:
  default:
    snyk_integration_id: <snyk_integration_id>
    snyk_org_id: <snyk_org_id>
  map_on: label # label or namespace
  label: com.azure.dev.image.system.teamproject # if map_on is label
  values:
    snyk_org_name_1:
      snyk_integration_id: <snyk_integration_id_1>
      snyk_org_id: <snyk_org_id_1>
    snyk_org_name_2:
      snyk_integration_id: <snyk_integration_id_2>
      snyk_org_id: <snyk_org_id_2>
targets_file_output_path: ./imported-targets.json
